# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 536bfb36dbc89a992e91d54445958654e919956bc63d8bfab1647fd03aac1917f9878fbec0b0aec4a303a26eddeead88183405f04bc469cacb8346afded58c16

test:
  secret_key_base: cbaef32d0f0b7a6a8ba1fd7ef1b4b6b0fbd795673c3ef23e641f6488e380d0a804e568a67f14a39d57cb88dfc2e1125a04d935067e44ca57768c0e2ec612123a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
